### ISSUE TITLE
Problems with installing minerl ==0.3.7 

### ISSUE THREAD

**Issue by sramichetty20019** [anishhdiwan/DQfD_Minecraft#1]
Hi ,

I am trying to learn to train my custom agents on Minerl, and for that, I wanted to start with this repository which explains the internals in a great way, kudos to you! and appreciate the effort

However when I am trying to download the older version of minerl ==0.3.7

I am getting the following error
![Screenshot 2024-04-27 at 12 45 29 PM](https://github.com/anishhdiwan/DQfD_Minecraft/assets/114448089/4a50033c-d9d0-4a2c-9834-3b090c5c2002)
I see that this is from the source code itself
How can make a clean installation please help me out in this regards
or how can I suppress this error

**Comment by anishhdiwan** [comment]
Hello Srinija

From my experience, mineRL seems to have changed versions several times with each version having its own set of dependencies. Unfortunately, this repository was mainly for research purposes and is not being actively maintained. In any case, you could try the following to try to get it to work.

1. I'd refer to the installation instructions [here](https://github.com/minerllabs/minerl) (as opposed to random docs that you might find online). For version 0.3.7 the docs are [here](https://minerl.readthedocs.io/en/v0.3.7/). Note that this repo uses version 0.4 so things are bound to be different. 
2. It's best to try this with a fresh OS installation (I'm not sure that mineRL works within virtual envs). If you have access to a Windows machine, I highly recommend WSL as it's easy to set up and can work as a pseudo-containerised environment. Docker might also work but I'm not sure whether it's tested. 
3. Make sure that you have the right GPU drivers.

Good luck!
